//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bankas.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accounts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Accounts()
        {
            this.Bills = new HashSet<Bills>();
        }
    
        public int ID { get; set; }
        public string Login { get; set; }
        public byte[] Pass { get; set; }
        public string IPReg { get; set; }
        public string IPLast { get; set; }
        public string Email { get; set; }
        public Nullable<int> IDStatus { get; set; }
        public string SecretWord { get; set; }
    
        public virtual Statuses Statuses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bills> Bills { get; set; }
        public virtual LegalPerson LegalPerson { get; set; }
        public virtual PhysicalPerson PhysicalPerson { get; set; }
    }
}
