//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bankas.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bills
    {
        public int ID { get; set; }
        public int IDOperation { get; set; }
        public int IDFilial { get; set; }
        public int IDType { get; set; }
        public Nullable<int> IDAccount { get; set; }
        public Nullable<System.DateTime> DataOpen { get; set; }
        public Nullable<System.DateTime> DataClose { get; set; }
        public Nullable<int> IDCity { get; set; }
    
        public virtual Accounts Accounts { get; set; }
        public virtual BillsTypes BillsTypes { get; set; }
        public virtual Cities Cities { get; set; }
        public virtual Filials Filials { get; set; }
        public virtual Operations Operations { get; set; }
    }
}
