//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bankas.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filials
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Filials()
        {
            this.Bills = new HashSet<Bills>();
        }
    
        public int ID { get; set; }
        public Nullable<int> NumberFilial { get; set; }
        public string Adress { get; set; }
        public string Phone { get; set; }
        public Nullable<System.TimeSpan> TimeOpen { get; set; }
        public Nullable<System.TimeSpan> TimeClose { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bills> Bills { get; set; }
    }
}
