//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bankas.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class LegalPerson
    {
        public int ID { get; set; }
        public string OGPH { get; set; }
        public string INN { get; set; }
        public string EGPUL { get; set; }
        public string LegalAdress { get; set; }
        public int IDPass { get; set; }
        public string Doverinnosti { get; set; }
    
        public virtual Accounts Accounts { get; set; }
        public virtual PasportAttorney PasportAttorney { get; set; }
    }
}
