//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bankas.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PasportAttorney
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PasportAttorney()
        {
            this.LegalPerson = new HashSet<LegalPerson>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Family { get; set; }
        public string MiddleName { get; set; }
        public string SerriaPas { get; set; }
        public string NumberPas { get; set; }
        public int Pol { get; set; }
    
        public virtual Gender Gender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LegalPerson> LegalPerson { get; set; }
    }
}
