//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bankas.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhysicalPerson
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Family { get; set; }
        public string MiddleName { get; set; }
        public string SeriaPas { get; set; }
        public string NumberPas { get; set; }
        public int IDGender { get; set; }
    
        public virtual Accounts Accounts { get; set; }
        public virtual Gender Gender { get; set; }
    }
}
